language: python
python:
- 2.7

dist: trusty

install: pip install -r spinnaker-monitoring-daemon/requirements.txt
script: gradle/buildViaTravis.sh

env:
  global:
  - secure: U2gIuvZT+iWnJw4ju8mGdx0yFjq8w2IJE2yWZECuqDdq0x01AVWTQJXTE8UndQsFGFPWvo3fOTgyJ6J6tvwhO29Cp6gPyw0+FsTa9QKpT6n52zuT/hoK9On53+FEmbanP1l1B2Mjn0T6h9DMOcFb5ixA7xhAWfZlOOmhYdb74DjkmT+fFm+tt+Ii48gKtV6y0PI1LTpcgucsUYUwhVN/Uoag9NDzbqVDhO/G/AUkxrAUfDcyCApM+d/3bjm+RrydiVdHq83G+GuTLebOd9Z1Lmm3t0MzwJTF18MKrIo9QHwbZMtJIlpArMMLYKwrpGLSwrQS87WRQohCopWFyfeVaGFeJ4989ig/aK6Uhd5kkovs9i7accm6aSD2rVWYhZQlMLh9uJWaZ2zNcUJbvmPoV0+EB4nW87Wf7ynkSbUivsTJwPagHw8b3esiZuUS9/Lh7bacCFPKc2cz5cvPhPhDCtsmONxjqnKAfkFwrBIaMNrOqrJi7xXpoKIaw1rhg2YIBNsxGgc3yZ17G2BN8QIEtMrwMGKINgReOCKMpuqRR9UhR1MfFqT6ahhtoMe3tirJYakIeeBkzrJVQNJm5BzsIVYDJySm6F7cT4PQo7DfJKAZppyMuTfQkDHsSozl0iZ6Lhc0Ii7j27Nkg7seDf3OawsXdHhEOJlrOLkKsHGe5vA=
  - secure: dMbRaaP11gJ2MQb7If0HFfx5MbvXZWjeprt0Te3+4jAZQhzG798hzntv9wq26LzlpEfqZjxYEJZCDuZZgyAJsy10P/u91GLFUd5FZKEUfu2tdI/8W0khpKXoocxdUZeAx7qt34EW31omnHEWpKwf/EqSApebl6+GToZ1+jCiR6T9Mpvx3N15DHL0fNFSBR1OsVqQYkt642fLOmFaMLXpO543SLRsJdl1OZi28GUQ3PklDb2qNqtXQoNCaZDpEbIDuLUif8ypjMJ4lxcdwICt5+NTEUtxesPm4Ysk+uqx+9mZp86c+2IWvxAn+bc6KIYZjcqRy19kOUK545rR9JxUL2TBWTav1bZB2GbhVRs5DAy4XERw1KOOcjMgCIOq9+spnasQCHeRjkw1wS76hP1h1J/6itvkSZs2vFTHXTEud9xVWBq6yKAdMx9gTs0XjKFPB1bk82Og3DCuMTFhfyzHUclr1Q2RLEOW0EiFA8AfuU7dOKMo7J6Ea0m+LWDLujFxd18nSJJaHp/1Ta24ghy28OpAo/ddWVOERyOliWKZ7XrL1CIGDm46xs9nrX0+qhSEQeL/fveXGtJv8at8YKXGqdxZ+Y4RgCglExjzM7qS+3NOI4XOMulGFNnx7dtEfNFrCMTrvwm3Tx1TRsqmPDjoxn7vXcze5JYmJuwECn2VLLY=
